# Generated by Django 4.2.11 on 2024-12-02 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('lugar', models.CharField(blank=True, max_length=100, null=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('codigo', models.CharField(max_length=10)),
                ('evento', models.ForeignKey(blank=True, db_column='evento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tarjetas.evento')),
            ],
        ),
    ]
