# Generated by Django 4.2.11 on 2024-12-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0003_tarjeta_dest_in_tarjeta_hora_fin_tarjeta_hora_ini_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjeta',
            old_name='triaje_fin',
            new_name='triaje',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='pos_psa',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
