# Generated by Django 4.2.11 on 2024-12-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0005_remove_psa_codigo_remove_psa_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='estado_traslado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('SOLICITADO', 'SOLICITADO'), ('GESTIONADO', 'GESTIONADO'), ('SALIDO_PSA', 'SALIDO_PSA'), ('REALIZADO', 'REALIZADO'), ('ALTA LUGAR', 'ALTA LUGAR')], max_length=32),
        ),
    ]
